version: "3.8"                                            # Версия docker-compose
services:
  backend:                                                # Имя сервиса - BACKEND
    build: .                                           # - Строить образ Docker из текущей директории
    env_file:                                             # Указание файла для подстановки переменных окружения
      - .env
    ports:                                                # Определение портов для перенаправления
      - "${BACKEND_OUTSIDE_PORT}:${BACKEND_INSIDE_PORT}"  # - Перенаправление CONTAINER_PORT на HOST_PORT, значения из .env
    command:                                              # Команда для запуска сервиса
      [
        "uvicorn", "main:app", "--reload",
        "--host", "0.0.0.0", "--port", "${BACKEND_INSIDE_PORT}",
        "--log-level", "debug"
      ]